apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: openmodelstudio
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-pvc
  namespace: openmodelstudio
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  namespace: openmodelstudio
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
